# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-10 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='projects/project_images')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
