# Generated by Django 2.0.2 on 2018-03-12 17:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary', models.CharField(default='Project summary.', help_text='A short summary of the project.', max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='projects/project_images')),
                ('color', models.TextField(blank=True, help_text='Background color for project overlay.')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.Category')),
            ],
            options={
                'verbose_name_plural': 'FinancialCategories',
            },
            bases=('projects.category',),
        ),
        migrations.CreateModel(
            name='TechnologyCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.Category')),
            ],
            options={
                'verbose_name_plural': 'FinancialCategories',
            },
            bases=('projects.category',),
        ),
        migrations.AddField(
            model_name='project',
            name='financial_categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.FinancialCategory'),
        ),
        migrations.AddField(
            model_name='project',
            name='technology_categories',
            field=models.ManyToManyField(to='projects.TechnologyCategory'),
        ),
    ]
