# Generated by Django 2.0.2 on 2018-03-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technologycategory',
            options={'verbose_name_plural': 'TechnologyCategories'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='financial_categories',
            new_name='financial_category',
        ),
    ]
