# Generated by Django 2.0.2 on 2018-03-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180125_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.TextField(blank=True, help_text='Background color for project overlay.'),
        ),
    ]
