# Generated by Django 2.0.2 on 2018-03-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180313_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='financial_category',
            new_name='financial_categories',
        ),
    ]
