# Generated by Django 2.0.2 on 2018-03-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.TextField(blank=True, default='null', help_text='Background color for project overlay.'),
        ),
    ]
