# Generated by Django 2.0.2 on 2018-03-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='logo',
        ),
    ]
