# Generated by Django 2.0.2 on 2018-03-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180309_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.TextField(blank=True, help_text='Background color for project overlay.'),
        ),
    ]
