# Generated by Django 2.0.2 on 2018-03-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180314_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, upload_to='projects/project_logos'),
        ),
    ]
