# Generated by Django 2.0.2 on 2018-03-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180309_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.CharField(default='Project summary.', help_text='A short summary of the project.', max_length=100),
        ),
    ]
